# Generated by Django 5.2 on 2025-04-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="temple",
            name="name",
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name="temple",
            name="raw_data",
            field=models.JSONField(default=None),
        ),
    ]
